#!/bin/bash

#Input - FROM TO BRANCH

TARGETBRANCH="deploy"
DSTDIR="/home/kib/www/"
SRCDIR="$(mktemp -d)"

read OLDREF NEWREF REFNAME
BRANCH=${REFNAME#refs/heads/}

if [ "$BRANCH" != "$TARGETBRANCH" ]; then
	echo "[log] Will only deploy branch $TARGETBRANCH, got $BRANCH ...exiting"
	exit
fi

#CHECKOUT SOUCE
GIT_WORK_TREE="$SRCDIR" git checkout -f $TARGETBRANCH

#PATCHING
echo "[log] Patching started"

#Update API path
cd "$SRCDIR/pageroot"
sed -i 's|kibdev.crabdance.com|konfliktspeliborlange.se|' js/kibservice.js admin/js/adminservice.js

#Update path for the page css files
cd "$SRCDIR/forum-theme/kib/theme"
sed -i 's|../../../pageroot|../../../..|g' stylesheet.css

#Start Bower to install deps
echo "[log] Starting 'bower install'"
cd "$SRCDIR/pageroot"
bower install

#COPY TO SRCDIR
echo "[log] Copying main web page files"
cp -r $SRCDIR/pageroot/* "$DSTDIR"

echo "[log] Copying forum theme"
[ ! -d "$DSTDIR/forum/styles/" ] && mkdir -p "$DSTDIR/forum/styles/"
cp -r "$SRCDIR/forum-theme/kib" "$DSTDIR/forum/styles/"

#CLEANUP
rm -r "$SRCDIR"